/*
Deployment script for db-mba-engenharia-dados

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "db-mba-engenharia-dados"
:setvar DefaultFilePrefix "db-mba-engenharia-dados"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
PRINT N'Creating [dbo].[TB_CATEGORIA_PRODUTO]...';


GO
CREATE TABLE [dbo].[TB_CATEGORIA_PRODUTO] (
    [CODIGO_CATEGORIA]      SMALLINT      IDENTITY (1, 1) NOT NULL,
    [CATEGORIA_PRODUTO]     VARCHAR (100) NOT NULL,
    [SUB_CATEGORIA_PRODUTO] VARCHAR (100) NOT NULL,
    [DT_INCLUSAO]           DATETIME      NOT NULL,
    CONSTRAINT [PK_TB_CATEGORIA_PRODUTO] PRIMARY KEY CLUSTERED ([CODIGO_CATEGORIA] ASC)
);


GO
PRINT N'Creating [dbo].[TB_CLIENTE]...';


GO
CREATE TABLE [dbo].[TB_CLIENTE] (
    [CODIGO_CLIENTE]     INT           IDENTITY (1, 1) NOT NULL,
    [NOME_CLIENTE]       VARCHAR (100) NOT NULL,
    [DATA_NASCIMENTO]    DATE          NOT NULL,
    [IDADE_CLIENTE]      TINYINT       NOT NULL,
    [DESCRICAO_ENDERECO] VARCHAR (200) NOT NULL,
    [NUMERO_ENDERECO]    SMALLINT      NOT NULL,
    [NOME_CIDADE]        VARCHAR (100) NOT NULL,
    [NUMERO_TELEFONE]    VARCHAR (30)  NOT NULL,
    [EMAIL_CLIENTE]      VARCHAR (100) NOT NULL,
    [OCUPACAO_CLIENTE]   VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TB_CLIENTE] PRIMARY KEY CLUSTERED ([CODIGO_CLIENTE] ASC)
);


GO
PRINT N'Creating [dbo].[TB_FORMA_PAGAMENTO]...';


GO
CREATE TABLE [dbo].[TB_FORMA_PAGAMENTO] (
    [CODIGO_FORMA_PAGAMENTO]    SMALLINT      IDENTITY (1, 1) NOT NULL,
    [DESCRICAO_FORMA_PAGAMENTO] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TB_FORMA_PAGAMENTO] PRIMARY KEY CLUSTERED ([CODIGO_FORMA_PAGAMENTO] ASC)
);


GO
PRINT N'Creating [dbo].[TB_ITEM_VENDA]...';


GO
CREATE TABLE [dbo].[TB_ITEM_VENDA] (
    [CODIGO_VENDA]   INT             NOT NULL,
    [CODIGO_PRODUTO] SMALLINT        NOT NULL,
    [VALOR_UNITARIO] DECIMAL (18, 2) NULL,
    [QUANTIDADE]     SMALLINT        NULL,
    [VALOR_FINAL]    DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_TB_ITEM_VENDA] PRIMARY KEY CLUSTERED ([CODIGO_VENDA] ASC, [CODIGO_PRODUTO] ASC)
);


GO
PRINT N'Creating [dbo].[TB_ITEM_VENDA].[IX_01]...';


GO
CREATE NONCLUSTERED INDEX [IX_01]
    ON [dbo].[TB_ITEM_VENDA]([CODIGO_VENDA] ASC);


GO
PRINT N'Creating [dbo].[TB_ITEM_VENDA].[IX_02]...';


GO
CREATE NONCLUSTERED INDEX [IX_02]
    ON [dbo].[TB_ITEM_VENDA]([CODIGO_PRODUTO] ASC);


GO
PRINT N'Creating [dbo].[TB_LOJA]...';


GO
CREATE TABLE [dbo].[TB_LOJA] (
    [CODIGO_LOJA_VENDEDOR] SMALLINT      IDENTITY (1, 1) NOT NULL,
    [CODIGO_LOJA]          SMALLINT      NOT NULL,
    [CODIGO_VENDEDOR]      SMALLINT      NOT NULL,
    [NOME_LOJA]            VARCHAR (100) NOT NULL,
    [LOCALIDADE_LOJA]      VARCHAR (100) NOT NULL,
    [TIPO_LOJA]            VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TB_LOJA] PRIMARY KEY CLUSTERED ([CODIGO_LOJA_VENDEDOR] ASC)
);


GO
PRINT N'Creating [dbo].[TB_PRODUTO]...';


GO
CREATE TABLE [dbo].[TB_PRODUTO] (
    [CODIGO_PRODUTO]    SMALLINT      IDENTITY (1, 1) NOT NULL,
    [DESCRICAO_PRODUTO] VARCHAR (100) NOT NULL,
    [CODIGO_CATEGORIA]  SMALLINT      NOT NULL,
    CONSTRAINT [PK_TB_PRODUTO] PRIMARY KEY CLUSTERED ([CODIGO_PRODUTO] ASC)
);


GO
PRINT N'Creating [dbo].[TB_PRODUTO].[IX_01]...';


GO
CREATE NONCLUSTERED INDEX [IX_01]
    ON [dbo].[TB_PRODUTO]([CODIGO_CATEGORIA] ASC);


GO
PRINT N'Creating [dbo].[TB_VENDA]...';


GO
CREATE TABLE [dbo].[TB_VENDA] (
    [CODIGO_VENDA]           INT             IDENTITY (1, 1) NOT NULL,
    [CODIGO_CLIENTE]         INT             NOT NULL,
    [CODIGO_FORMA_PAGAMENTO] SMALLINT        NOT NULL,
    [CODIGO_LOJA_VENDEDOR]   SMALLINT        NOT NULL,
    [DATA_VENDA]             DATETIME        NOT NULL,
    [VALOR_FINAL]            DECIMAL (18, 2) NOT NULL,
    [TIPO_PAGAMENTO]         VARCHAR (100)   NOT NULL,
    CONSTRAINT [PK_TB_VENDA] PRIMARY KEY CLUSTERED ([CODIGO_VENDA] ASC)
);


GO
PRINT N'Creating [dbo].[TB_VENDA].[IX_01]...';


GO
CREATE NONCLUSTERED INDEX [IX_01]
    ON [dbo].[TB_VENDA]([CODIGO_CLIENTE] ASC);


GO
PRINT N'Creating [dbo].[TB_VENDA].[IX_02]...';


GO
CREATE NONCLUSTERED INDEX [IX_02]
    ON [dbo].[TB_VENDA]([CODIGO_FORMA_PAGAMENTO] ASC);


GO
PRINT N'Creating [dbo].[TB_VENDEDOR]...';


GO
CREATE TABLE [dbo].[TB_VENDEDOR] (
    [CODIGO_VENDEDOR] SMALLINT      IDENTITY (1, 1) NOT NULL,
    [NOME_VENDEDOR]   VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_CODIGO_VENDEDOR] PRIMARY KEY CLUSTERED ([CODIGO_VENDEDOR] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[TB_CATEGORIA_PRODUTO]...';


GO
ALTER TABLE [dbo].[TB_CATEGORIA_PRODUTO]
    ADD DEFAULT (getdate()) FOR [DT_INCLUSAO];


GO
PRINT N'Creating [dbo].[FK_TB_VENDA_ITEM_VENDA]...';


GO
ALTER TABLE [dbo].[TB_ITEM_VENDA] WITH NOCHECK
    ADD CONSTRAINT [FK_TB_VENDA_ITEM_VENDA] FOREIGN KEY ([CODIGO_VENDA]) REFERENCES [dbo].[TB_VENDA] ([CODIGO_VENDA]);


GO
PRINT N'Creating [dbo].[FK_TB_ITEM_VENDA_PRODUTO]...';


GO
ALTER TABLE [dbo].[TB_ITEM_VENDA] WITH NOCHECK
    ADD CONSTRAINT [FK_TB_ITEM_VENDA_PRODUTO] FOREIGN KEY ([CODIGO_PRODUTO]) REFERENCES [dbo].[TB_PRODUTO] ([CODIGO_PRODUTO]);


GO
PRINT N'Creating [dbo].[FK_TB_VENDEDOR_LOJA]...';


GO
ALTER TABLE [dbo].[TB_LOJA] WITH NOCHECK
    ADD CONSTRAINT [FK_TB_VENDEDOR_LOJA] FOREIGN KEY ([CODIGO_VENDEDOR]) REFERENCES [dbo].[TB_VENDEDOR] ([CODIGO_VENDEDOR]);


GO
PRINT N'Creating [dbo].[FK_TB_PRODUTO_CATEGORIA_PRODUTO]...';


GO
ALTER TABLE [dbo].[TB_PRODUTO] WITH NOCHECK
    ADD CONSTRAINT [FK_TB_PRODUTO_CATEGORIA_PRODUTO] FOREIGN KEY ([CODIGO_CATEGORIA]) REFERENCES [dbo].[TB_CATEGORIA_PRODUTO] ([CODIGO_CATEGORIA]);


GO
PRINT N'Creating [dbo].[FK_TB_VENDA_CLIENTE]...';


GO
ALTER TABLE [dbo].[TB_VENDA] WITH NOCHECK
    ADD CONSTRAINT [FK_TB_VENDA_CLIENTE] FOREIGN KEY ([CODIGO_CLIENTE]) REFERENCES [dbo].[TB_CLIENTE] ([CODIGO_CLIENTE]);


GO
PRINT N'Creating [dbo].[FK_TB_VENDA_FORMA_PAGAMENTO]...';


GO
ALTER TABLE [dbo].[TB_VENDA] WITH NOCHECK
    ADD CONSTRAINT [FK_TB_VENDA_FORMA_PAGAMENTO] FOREIGN KEY ([CODIGO_FORMA_PAGAMENTO]) REFERENCES [dbo].[TB_FORMA_PAGAMENTO] ([CODIGO_FORMA_PAGAMENTO]);


GO
PRINT N'Creating [dbo].[FK_TB_VENDA_LOJA_VENDEDOR]...';


GO
ALTER TABLE [dbo].[TB_VENDA] WITH NOCHECK
    ADD CONSTRAINT [FK_TB_VENDA_LOJA_VENDEDOR] FOREIGN KEY ([CODIGO_LOJA_VENDEDOR]) REFERENCES [dbo].[TB_LOJA] ([CODIGO_LOJA_VENDEDOR]);


GO
PRINT N'Creating [dbo].[TB_CATEGORIA_PRODUTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Armazena informações das categorias dos produtos', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CATEGORIA_PRODUTO';


GO
PRINT N'Creating [dbo].[TB_CATEGORIA_PRODUTO].[CODIGO_CATEGORIA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código da Categoria do Produto.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CATEGORIA_PRODUTO', @level2type = N'COLUMN', @level2name = N'CODIGO_CATEGORIA';


GO
PRINT N'Creating [dbo].[TB_CATEGORIA_PRODUTO].[CATEGORIA_PRODUTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Descrição da Categoria do Produto.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CATEGORIA_PRODUTO', @level2type = N'COLUMN', @level2name = N'CATEGORIA_PRODUTO';


GO
PRINT N'Creating [dbo].[TB_CATEGORIA_PRODUTO].[SUB_CATEGORIA_PRODUTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Descrição da Sub-Categoria do Produto.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CATEGORIA_PRODUTO', @level2type = N'COLUMN', @level2name = N'SUB_CATEGORIA_PRODUTO';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Armazena informações de clientes.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[CODIGO_CLIENTE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código do Cliente.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'CODIGO_CLIENTE';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[NOME_CLIENTE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nome do Cliente.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'NOME_CLIENTE';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[DATA_NASCIMENTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Data de Nascimento do Cliente', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'DATA_NASCIMENTO';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[IDADE_CLIENTE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Idade do Cliente', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'IDADE_CLIENTE';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[DESCRICAO_ENDERECO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Endereço do Cliente', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'DESCRICAO_ENDERECO';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[NUMERO_ENDERECO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Número do Endereço', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'NUMERO_ENDERECO';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[NOME_CIDADE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Cidade', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'NOME_CIDADE';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[NUMERO_TELEFONE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Telefone', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'NUMERO_TELEFONE';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[EMAIL_CLIENTE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'E-mail do cliente', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'EMAIL_CLIENTE';


GO
PRINT N'Creating [dbo].[TB_CLIENTE].[OCUPACAO_CLIENTE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Ocupação do Cliente', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_CLIENTE', @level2type = N'COLUMN', @level2name = N'OCUPACAO_CLIENTE';


GO
PRINT N'Creating [dbo].[TB_FORMA_PAGAMENTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Armazena informações de forma de pagamento.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_FORMA_PAGAMENTO';


GO
PRINT N'Creating [dbo].[TB_FORMA_PAGAMENTO].[CODIGO_FORMA_PAGAMENTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código da Forma de Pagamento na Tabela TB_FORMA_PAGAMENTO.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_FORMA_PAGAMENTO', @level2type = N'COLUMN', @level2name = N'CODIGO_FORMA_PAGAMENTO';


GO
PRINT N'Creating [dbo].[TB_FORMA_PAGAMENTO].[DESCRICAO_FORMA_PAGAMENTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Descrição da Forma de Pagamento na Tabela TB_FORMA_PAGAMENTO.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_FORMA_PAGAMENTO', @level2type = N'COLUMN', @level2name = N'DESCRICAO_FORMA_PAGAMENTO';


GO
PRINT N'Creating [dbo].[TB_ITEM_VENDA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Armazena informações sobre os itens que foram vendidos.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_ITEM_VENDA';


GO
PRINT N'Creating [dbo].[TB_ITEM_VENDA].[CODIGO_VENDA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código da Venda', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_ITEM_VENDA', @level2type = N'COLUMN', @level2name = N'CODIGO_VENDA';


GO
PRINT N'Creating [dbo].[TB_ITEM_VENDA].[CODIGO_PRODUTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código do Produto', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_ITEM_VENDA', @level2type = N'COLUMN', @level2name = N'CODIGO_PRODUTO';


GO
PRINT N'Creating [dbo].[TB_ITEM_VENDA].[VALOR_UNITARIO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Valor Unitário do Produto', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_ITEM_VENDA', @level2type = N'COLUMN', @level2name = N'VALOR_UNITARIO';


GO
PRINT N'Creating [dbo].[TB_ITEM_VENDA].[QUANTIDADE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Quantidade do Produto Vendido', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_ITEM_VENDA', @level2type = N'COLUMN', @level2name = N'QUANTIDADE';


GO
PRINT N'Creating [dbo].[TB_ITEM_VENDA].[VALOR_FINAL].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Valor Final do Produto Vendido', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_ITEM_VENDA', @level2type = N'COLUMN', @level2name = N'VALOR_FINAL';


GO
PRINT N'Creating [dbo].[TB_LOJA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Armazena informações de lojas.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_LOJA';


GO
PRINT N'Creating [dbo].[TB_LOJA].[CODIGO_LOJA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código da Loja.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_LOJA', @level2type = N'COLUMN', @level2name = N'CODIGO_LOJA';


GO
PRINT N'Creating [dbo].[TB_LOJA].[NOME_LOJA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nome da Loja.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_LOJA', @level2type = N'COLUMN', @level2name = N'NOME_LOJA';


GO
PRINT N'Creating [dbo].[TB_LOJA].[LOCALIDADE_LOJA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Localidade da Loja.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_LOJA', @level2type = N'COLUMN', @level2name = N'LOCALIDADE_LOJA';


GO
PRINT N'Creating [dbo].[TB_LOJA].[TIPO_LOJA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipo da Loja.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_LOJA', @level2type = N'COLUMN', @level2name = N'TIPO_LOJA';


GO
PRINT N'Creating [dbo].[TB_PRODUTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Armazena informações de produtos.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_PRODUTO';


GO
PRINT N'Creating [dbo].[TB_PRODUTO].[CODIGO_PRODUTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código do Produto.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_PRODUTO', @level2type = N'COLUMN', @level2name = N'CODIGO_PRODUTO';


GO
PRINT N'Creating [dbo].[TB_PRODUTO].[DESCRICAO_PRODUTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Descrição do Produto.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_PRODUTO', @level2type = N'COLUMN', @level2name = N'DESCRICAO_PRODUTO';


GO
PRINT N'Creating [dbo].[TB_PRODUTO].[CODIGO_CATEGORIA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Categoria do Produto.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_PRODUTO', @level2type = N'COLUMN', @level2name = N'CODIGO_CATEGORIA';


GO
PRINT N'Creating [dbo].[TB_VENDA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Armazenada informações de vendas.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDA';


GO
PRINT N'Creating [dbo].[TB_VENDA].[CODIGO_VENDA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código da Venda.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDA', @level2type = N'COLUMN', @level2name = N'CODIGO_VENDA';


GO
PRINT N'Creating [dbo].[TB_VENDA].[CODIGO_CLIENTE].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código do Cliente', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDA', @level2type = N'COLUMN', @level2name = N'CODIGO_CLIENTE';


GO
PRINT N'Creating [dbo].[TB_VENDA].[CODIGO_FORMA_PAGAMENTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Forma de Pagamento', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDA', @level2type = N'COLUMN', @level2name = N'CODIGO_FORMA_PAGAMENTO';


GO
PRINT N'Creating [dbo].[TB_VENDA].[DATA_VENDA].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Data da Venda', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDA', @level2type = N'COLUMN', @level2name = N'DATA_VENDA';


GO
PRINT N'Creating [dbo].[TB_VENDA].[VALOR_FINAL].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Valor Total da Venda', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDA', @level2type = N'COLUMN', @level2name = N'VALOR_FINAL';


GO
PRINT N'Creating [dbo].[TB_VENDA].[TIPO_PAGAMENTO].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipo de Pagamento', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDA', @level2type = N'COLUMN', @level2name = N'TIPO_PAGAMENTO';


GO
PRINT N'Creating [dbo].[TB_VENDEDOR].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Armazena informações de vendedores', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDEDOR';


GO
PRINT N'Creating [dbo].[TB_VENDEDOR].[CODIGO_VENDEDOR].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Código do Vendedor.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDEDOR', @level2type = N'COLUMN', @level2name = N'CODIGO_VENDEDOR';


GO
PRINT N'Creating [dbo].[TB_VENDEDOR].[NOME_VENDEDOR].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nome do Vendedor.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TB_VENDEDOR', @level2type = N'COLUMN', @level2name = N'NOME_VENDEDOR';


GO
