CREATE TABLE [Bem] (
  [NR_CPF_CANDIDATO] char(11) NOT NULL,
  [NR_ORDEM_BEM_CANDIDATO] smallint NOT NULL,
  [CD_TIPO_BEM_CANDIDATO] tinyint NULL,
  [DS_BEM_CANDIDATO] varchar(255) NULL,
  [VR_BEM_CANDIDATO] decimal(10,2) NULL,
  [DT_ULT_ATUAL_BEM_CANDIDATO] date NULL,
  [HH_ULT_ATUAL_BEM_CANDIDATO] time NULL,
  PRIMARY KEY CLUSTERED ([NR_CPF_CANDIDATO], [NR_ORDEM_BEM_CANDIDATO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Candidato] (
  [NR_CPF_CANDIDATO] char(11) NOT NULL,
  [DS_EMAIL] varchar(255) NULL,
  [NM_CANDIDATO] varchar(255) NULL,
  [NM_SOCIAL_CANDIDATO] varchar(255) NULL,
  [SG_UF_NASCIMENTO] char(2) NULL,
  [DT_NASCIMENTO] date NULL,
  [NR_TITULO_ELEITORAL_CANDIDATO] varchar(15) NULL,
  [CD_GENERO] tinyint NULL,
  [CD_GRAU_INSTRUCAO] tinyint NULL,
  [CD_ESTADO_CIVIL] tinyint NULL,
  [CD_COR_RACA] char(2) NULL,
  [CD_OCUPACAO] smallint NULL,
  PRIMARY KEY CLUSTERED ([NR_CPF_CANDIDATO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Candidatura] (
  [CD_ELEICAO] smallint NOT NULL,
  [NR_CPF_CANDIDATO] char(11) NOT NULL,
  [SG_UF] char(2) NULL,
  [SG_UE] char(5) NULL,
  [CD_CARGO] tinyint NULL,
  [SQ_CANDIDATO] char(11) NULL,
  [NR_CANDIDATO] int NULL,
  [NM_URNA_CANDIDATO] varchar(100) NULL,
  [CD_SITUACAO_CANDIDATURA] tinyint NULL,
  [TP_AGREMIACAO] varchar(255) NULL,
  [NR_PARTIDO] tinyint NULL,
  [NR_FEDERACAO] smallint NULL,
  [SQ_COLIGACAO] char(11) NULL,
  [CD_SIT_TOT_TURNO] tinyint NULL,
  [CD_SITUACAO_DIPLOMA] smallint NULL,
  [CD_SITUACAO_CASSACAO] smallint NULL,
  [CD_SITUACAO_JULGAMENTO] smallint NULL,
  [CD_DETALHE_SITUACAO_CAND] smallint NULL,
  PRIMARY KEY CLUSTERED ([CD_ELEICAO], [NR_CPF_CANDIDATO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Cargo] (
  [CD_CARGO] tinyint NOT NULL,
  [DS_CARGO] varchar(30) NULL,
  PRIMARY KEY CLUSTERED ([CD_CARGO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Coligacao] (
  [SQ_COLIGACAO] char(11) NOT NULL,
  [NM_COLIGACAO] varchar(50) NULL,
  PRIMARY KEY CLUSTERED ([SQ_COLIGACAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Composicao_Coligacao] (
  [SQ_COLIGACAO] char(11) NOT NULL,
  [NR_PARTIDO] tinyint NOT NULL,
  PRIMARY KEY CLUSTERED ([SQ_COLIGACAO], [NR_PARTIDO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Composicao_Federacao] (
  [NR_FEDERACAO] smallint NOT NULL,
  [NR_PARTIDO] tinyint NOT NULL,
  PRIMARY KEY CLUSTERED ([NR_FEDERACAO], [NR_PARTIDO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Cor_Raca] (
  [CD_COR_RACA] char(2) NOT NULL,
  [DS_COR_RACA] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_COR_RACA])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Detalhe_Situacao_Candidato] (
  [CD_DETALHE_SITUACAO_CAND] smallint NOT NULL,
  [DS_DETALHE_SITUACAO_CAND] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_DETALHE_SITUACAO_CAND])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Eleicao] (
  [CD_ELEICAO] smallint NOT NULL,
  [CD_TIPO_ELEICAO] tinyint NULL,
  [TP_ABRANGENCIA] varchar(30) NULL,
  [ANO_ELEICAO] smallint NULL,
  [DS_ELEICAO] varchar(100) NULL,
  [DT_ELEICAO] date NULL,
  PRIMARY KEY CLUSTERED ([CD_ELEICAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Estado_Civil] (
  [CD_ESTADO_CIVIL] tinyint NOT NULL,
  [DS_ESTADO_CIVIL] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_ESTADO_CIVIL])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Federacao] (
  [NR_FEDERACAO] smallint NOT NULL,
  [NM_FEDERACAO] varchar(255) NULL,
  [SG_FEDERACAO] varchar(30) NULL,
  PRIMARY KEY CLUSTERED ([NR_FEDERACAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Grau_Instrucao] (
  [CD_GRAU_INSTRUCAO] tinyint NOT NULL,
  [DS_GRAU_INSTRUCAO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_GRAU_INSTRUCAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Municipio] (
  [CD_MUNICIPIO] smallint NOT NULL,
  [NM_MUNICIPIO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_MUNICIPIO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Ocupacao] (
  [CD_OCUPACAO] smallint NOT NULL,
  [DS_OCUPACAO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_OCUPACAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Partido] (
  [NR_PARTIDO] tinyint NOT NULL,
  [SG_PARTIDO] varchar(20) NULL,
  [NM_PARTIDO] varchar(50) NULL,
  PRIMARY KEY CLUSTERED ([NR_PARTIDO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Situacao_Candidatura] (
  [CD_SITUACAO_CANDIDATURA] tinyint NOT NULL,
  [DS_SITUACAO_CANDIDATURA] varchar(100) NULL,
  PRIMARY KEY CLUSTERED ([CD_SITUACAO_CANDIDATURA])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Situacao_Cassacao] (
  [CD_SITUACAO_CASSACAO] smallint NOT NULL,
  [DS_SITUACAO_CASSACAO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_SITUACAO_CASSACAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Situacao_Diplomacao] (
  [CD_SITUACAO_DIPLOMA] smallint NOT NULL,
  [DS_SITUACAO_DIPLOMA] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_SITUACAO_DIPLOMA])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Situacao_Julgamento] (
  [CD_SITUACAO_JULGAMENTO] smallint NOT NULL,
  [DS_SITUACAO_JULGAMENTO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_SITUACAO_JULGAMENTO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Situacao_Totalizacao] (
  [CD_SIT_TOT_TURNO] tinyint NOT NULL,
  [DS_SIT_TOT_TURNO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_SIT_TOT_TURNO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Tipo_Bem] (
  [CD_TIPO_BEM_CANDIDATO] tinyint NOT NULL,
  [DS_TIPO_BEM_CANDIDATO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_TIPO_BEM_CANDIDATO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Tipo_Eleicao] (
  [CD_TIPO_ELEICAO] tinyint NOT NULL,
  [NM_TIPO_ELEICAO] varchar(30) NULL,
  PRIMARY KEY CLUSTERED ([CD_TIPO_ELEICAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Unidade_Eleitoral] (
  [SG_UE] char(5) NOT NULL,
  [NM_UE] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([SG_UE])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Voto] (
  [CD_ELEICAO] smallint NOT NULL,
  [NR_CPF_CANDIDATO] char(11) NOT NULL,
  [CD_MUNICIPIO] smallint NOT NULL,
  [NR_ZONA] tinyint NOT NULL,
  [ST_VOTO_EM_TRANSITO] char(1) NULL,
  [QT_VOTOS_NOMINAIS] int NULL,
  [NM_TIPO_DESTINACAO_VOTOS] varchar(10) NULL,
  [QT_VOTOS_NOMINAIS_VALIDOS] int NULL,
  PRIMARY KEY CLUSTERED ([CD_ELEICAO], [NR_CPF_CANDIDATO], [CD_MUNICIPIO], [NR_ZONA])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

ALTER TABLE [Bem] ADD CONSTRAINT [FK_BEM_CANDIDATO] FOREIGN KEY ([NR_CPF_CANDIDATO]) REFERENCES [Candidato] ([NR_CPF_CANDIDATO])
GO
ALTER TABLE [Bem] ADD CONSTRAINT [FK_BEM_TIPO_BEM] FOREIGN KEY ([CD_TIPO_BEM_CANDIDATO]) REFERENCES [Tipo_Bem] ([CD_TIPO_BEM_CANDIDATO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_OCUPACAO] FOREIGN KEY ([CD_OCUPACAO]) REFERENCES [Ocupacao] ([CD_OCUPACAO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_CORRACA] FOREIGN KEY ([CD_COR_RACA]) REFERENCES [Cor_Raca] ([CD_COR_RACA])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_GRAU_INSTRUCAO] FOREIGN KEY ([CD_GRAU_INSTRUCAO]) REFERENCES [Grau_Instrucao] ([CD_GRAU_INSTRUCAO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_ESTADO_CIVIL] FOREIGN KEY ([CD_ESTADO_CIVIL]) REFERENCES [Estado_Civil] ([CD_ESTADO_CIVIL])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_ELEICAO] FOREIGN KEY ([CD_ELEICAO]) REFERENCES [Eleicao] ([CD_ELEICAO])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_CANDIDATO] FOREIGN KEY ([NR_CPF_CANDIDATO]) REFERENCES [Candidato] ([NR_CPF_CANDIDATO])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_PARTIDO] FOREIGN KEY ([NR_PARTIDO]) REFERENCES [Partido] ([NR_PARTIDO])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_SITUACAO_CANDIDATURA] FOREIGN KEY ([CD_SITUACAO_CANDIDATURA]) REFERENCES [Situacao_Candidatura] ([CD_SITUACAO_CANDIDATURA])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_FEDERACAO] FOREIGN KEY ([NR_FEDERACAO]) REFERENCES [Federacao] ([NR_FEDERACAO])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_COLIGACAO] FOREIGN KEY ([SQ_COLIGACAO]) REFERENCES [Coligacao] ([SQ_COLIGACAO])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_UNIDADE_ELEITORAL] FOREIGN KEY ([SG_UE]) REFERENCES [Unidade_Eleitoral] ([SG_UE])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_CARGO] FOREIGN KEY ([CD_CARGO]) REFERENCES [Cargo] ([CD_CARGO])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_SITUACAO_DIPLOMACAO] FOREIGN KEY ([CD_SITUACAO_DIPLOMA]) REFERENCES [Situacao_Diplomacao] ([CD_SITUACAO_DIPLOMA])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_SITUACAO_JULGAMENTO] FOREIGN KEY ([CD_SITUACAO_JULGAMENTO]) REFERENCES [Situacao_Julgamento] ([CD_SITUACAO_JULGAMENTO])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_TOTALIZACAO_TURNO] FOREIGN KEY ([CD_SIT_TOT_TURNO]) REFERENCES [Situacao_Totalizacao] ([CD_SIT_TOT_TURNO])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_DETALHE_SITUACAO_CANDIDATO] FOREIGN KEY ([CD_DETALHE_SITUACAO_CAND]) REFERENCES [Detalhe_Situacao_Candidato] ([CD_DETALHE_SITUACAO_CAND])
GO
ALTER TABLE [Candidatura] ADD CONSTRAINT [FK_CANDIDATURA_SITUACAO_CASSACAO] FOREIGN KEY ([CD_SITUACAO_CASSACAO]) REFERENCES [Situacao_Cassacao] ([CD_SITUACAO_CASSACAO])
GO
ALTER TABLE [Candidatura] NOCHECK CONSTRAINT [FK_CANDIDATURA_SITUACAO_JULGAMENTO]
GO
ALTER TABLE [Composicao_Coligacao] ADD CONSTRAINT [FK_COMPOSICAO_COLIGACAO_COLIGACAO] FOREIGN KEY ([SQ_COLIGACAO]) REFERENCES [Coligacao] ([SQ_COLIGACAO])
GO
ALTER TABLE [Composicao_Coligacao] ADD CONSTRAINT [FK_COMPOSICAO_COLIGACAO_PARTIDO] FOREIGN KEY ([NR_PARTIDO]) REFERENCES [Partido] ([NR_PARTIDO])
GO
ALTER TABLE [Composicao_Federacao] ADD CONSTRAINT [FK_FEDERACAO] FOREIGN KEY ([NR_FEDERACAO]) REFERENCES [Federacao] ([NR_FEDERACAO])
GO
ALTER TABLE [Composicao_Federacao] ADD CONSTRAINT [FK_PARTIDO] FOREIGN KEY ([NR_PARTIDO]) REFERENCES [Partido] ([NR_PARTIDO])
GO
ALTER TABLE [Eleicao] ADD CONSTRAINT [FK_TIPO_ELEICAO] FOREIGN KEY ([CD_TIPO_ELEICAO]) REFERENCES [Tipo_Eleicao] ([CD_TIPO_ELEICAO])
GO
ALTER TABLE [Voto] ADD CONSTRAINT [FK_VOTO_ELEICAO] FOREIGN KEY ([CD_ELEICAO]) REFERENCES [Eleicao] ([CD_ELEICAO])
GO
ALTER TABLE [Voto] ADD CONSTRAINT [FK_VOTO_CANDIDATO] FOREIGN KEY ([NR_CPF_CANDIDATO]) REFERENCES [Candidato] ([NR_CPF_CANDIDATO])
GO
ALTER TABLE [Voto] ADD CONSTRAINT [FK_VOTO_MUNICIPIO] FOREIGN KEY ([CD_MUNICIPIO]) REFERENCES [Municipio] ([CD_MUNICIPIO])
GO

