CREATE TABLE candidato (
    SQ_CANDIDATO INT PRIMARY KEY,
    NM_URNA_CANDIDATO VARCHAR(100),
    NM_SOCIAL_CANDIDATO VARCHAR(100),
    CD_SITUACAO_CANDIDATURA INT,
    DS_SITUACAO_CANDIDATURA VARCHAR(100),
    CD_DETALHE_SITUACAO_CAND INT,
    DS_DETALHE_SITUACAO_CAND VARCHAR(100),
    CD_SITUACAO_JULGAMENTO INT,
    DS_SITUACAO_JULGAMENTO VARCHAR(100),
    CD_SITUACAO_CASSACAO INT,
    DS_SITUACAO_CASSACAO VARCHAR(100),
    CD_SITUACAO_DIPLOMA INT,
    DS_SITUACAO_DIPLOMA VARCHAR(100),
    TP_AGREMIACAO VARCHAR(50),
    NR_PARTIDO INT,
    SG_PARTIDO VARCHAR(10),
    NM_PARTIDO VARCHAR(100),
    NR_FEDERACAO INT,
    NM_FEDERACAO VARCHAR(100),
    SG_FEDERACAO VARCHAR(10),
    DS_COMP TEXT
);

CREATE TABLE bem_candidato (
    SQ_CANDIDATO INT,
    NR_ORDEM_BEM_CANDIDATO INT,
    CD_TIPO_BEM_CANDIDATO INT,
    DS_TIPO_BEM_CANDIDATO VARCHAR(100),
    VR_BEM_CANDIDATO DECIMAL(18, 2),
    DT_ULT_ATUAL_BEM_CANDIDATO DATE,
    HH_ULT_ATUAL_BEM_CANDIDATO TIME,
    PRIMARY KEY (SQ_CANDIDATO, NR_ORDEM_BEM_CANDIDATO),
    FOREIGN KEY (SQ_CANDIDATO) REFERENCES candidato(SQ_CANDIDATO)
);

CREATE TABLE rede_social (
    SQ_CANDIDATO INT,
    NR_ORDEM_REDE_SOCIAL INT,
    DS_URL VARCHAR(255),
    PRIMARY KEY (SQ_CANDIDATO, NR_ORDEM_REDE_SOCIAL),
    FOREIGN KEY (SQ_CANDIDATO) REFERENCES candidato(SQ_CANDIDATO)
);

CREATE TABLE motivo_cassacao (
    SQ_CANDIDATO INT,
    CD_SITUACAO_CASSACAO INT,
    DS_SITUACAO_CASSACAO VARCHAR(100),
    PRIMARY KEY (SQ_CANDIDATO, CD_SITUACAO_CASSACAO),
    FOREIGN KEY (SQ_CANDIDATO) REFERENCES candidato(SQ_CANDIDATO)
);

CREATE TABLE votacao (
    SQ_CANDIDATO INT,
    NR_TURNO INT,
    CD_ELEICAO INT,
    ANO_ELEICAO INT,
    TP_ABRANGENCIA VARCHAR(50),
    SG_UF VARCHAR(2),
    SG_UE VARCHAR(2),
    CD_MUNICIPIO INT,
    NM_MUNICIPIO VARCHAR(100),
    NR_ZONA INT,
    CD_CARGO INT,
    DS_CARGO VARCHAR(100),
    NR_CANDIDATO INT,
    ST_VOTO_EM_TRANSITO BOOLEAN,
    QT_VOTOS_NOMINAIS INT,
    NM_TIPO_DESTINACAO_VOTOS VARCHAR(100),
    QT_VOTOS_NOMINAIS_VALIDOS INT,
    CD_SIT_TOT_TURNO INT,
    DS_SIT_TOT_TURNO VARCHAR(100),
    PRIMARY KEY (SQ_CANDIDATO, NR_TURNO, CD_ELEICAO),
    FOREIGN KEY (SQ_CANDIDATO) REFERENCES candidato(SQ_CANDIDATO)
);
