IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'SiriusTSE')
BEGIN
    CREATE DATABASE SiriusTSE;
END;
GO 

USE SiriusTSE;
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'UF')
DROP TABLE dbo.UF;
GO

CREATE TABLE UF (
    SG_UF CHAR(2),
    SG_UE VARCHAR(10),
    NM_UE VARCHAR(100),
	PRIMARY KEY (SG_UF,SG_UE)
);

PRINT 'Criação da tabela UF concluída! ^-^';

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CARGO')
DROP TABLE dbo.CARGO;
GO

CREATE TABLE CARGO (
    CD_CARGO INT PRIMARY KEY,
    DS_CARGO VARCHAR(100)
);
PRINT 'Criação da tabela CARGO concluída! ^-^';

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SITUACAO_CANDIDATURA')
DROP TABLE dbo.SITUACAO_CANDIDATURA;
GO

CREATE TABLE SITUACAO_CANDIDATURA (
    CD_SITUACAO_CANDIDATURA INT PRIMARY KEY,
    DS_SITUACAO_CANDIDATURA VARCHAR(100)
);
PRINT 'Criação da tabela SITUACAO_CANDIDATURA concluída! ^-^';

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PARTIDO')
DROP TABLE dbo.PARTIDO;
GO

CREATE TABLE PARTIDO (
    NR_PARTIDO INT PRIMARY KEY,
    SG_PARTIDO VARCHAR(50),
    NM_PARTIDO VARCHAR(255)
);
PRINT 'Criação da tabela PARTIDO concluída! ^-^';

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'GRAU_INSTRUCAO')
DROP TABLE dbo.GRAU_INSTRUCAO;
GO

CREATE TABLE GRAU_INSTRUCAO (
    CD_GRAU_INSTRUCAO INT PRIMARY KEY,
    DS_GRAU_INSTRUCAO VARCHAR(100)
);
PRINT 'Criação da tabela GRAU_INSTRUCAO concluída! ^-^';

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'OCUPACAO')
DROP TABLE dbo.OCUPACAO;
GO

CREATE TABLE OCUPACAO (
    CD_OCUPACAO INT PRIMARY KEY,
    DS_OCUPACAO VARCHAR(100)
);
PRINT 'Criação da tabela OCUPACAO concluída! ^-^';

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ELEICAO')
DROP TABLE dbo.ELEICAO;
GO

CREATE TABLE ELEICAO (
    CD_ELEICAO INT PRIMARY KEY,
    ANO_ELEICAO INT,
    DT_ELEICAO DATE,
    CD_TIPO_ELEICAO INT,
    NM_TIPO_ELEICAO VARCHAR(100),
    TP_ABRANGENCIA_ELEICAO VARCHAR(50)
);
PRINT 'Criação da tabela ELEICAO concluída! ^-^';

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CANDIDATO')
DROP TABLE dbo.CANDIDATO;
GO

CREATE TABLE CANDIDATO (
    SQ_CANDIDATO BIGINT,
	NR_TURNO INT,
    NM_CANDIDATO VARCHAR(200),
    NM_URNA_CANDIDATO VARCHAR(100),
    NM_SOCIAL_CANDIDATO VARCHAR(100),
    NR_CPF_CANDIDATO VARCHAR(11),
    DS_EMAIL VARCHAR(200),
    CD_GRAU_INSTRUCAO INT,
    CD_OCUPACAO INT,
    SG_UF CHAR(2),
    SG_UE VARCHAR(10), 
    CD_CARGO INT,
    CD_SITUACAO_CANDIDATURA INT,
    CD_ELEICAO INT,
	NR_PARTIDO INT,
	PRIMARY KEY (SQ_CANDIDATO, NR_TURNO),
    FOREIGN KEY (CD_GRAU_INSTRUCAO) REFERENCES GRAU_INSTRUCAO(CD_GRAU_INSTRUCAO),
    FOREIGN KEY (CD_OCUPACAO) REFERENCES OCUPACAO(CD_OCUPACAO),
    FOREIGN KEY (SG_UF, SG_UE) REFERENCES UF(SG_UF, SG_UE), 
    FOREIGN KEY (CD_CARGO) REFERENCES CARGO(CD_CARGO),
    FOREIGN KEY (CD_SITUACAO_CANDIDATURA) REFERENCES SITUACAO_CANDIDATURA(CD_SITUACAO_CANDIDATURA),
    FOREIGN KEY (CD_ELEICAO) REFERENCES ELEICAO(CD_ELEICAO),
	FOREIGN KEY (NR_PARTIDO) REFERENCES PARTIDO(NR_PARTIDO)
);
PRINT 'Criação da tabela CANDIDATO concluída! ^-^';