CREATE VIEW Vw_Candidatos_Informacoes AS
SELECT 
    C.NM_CANDIDATO,
    O.DS_OCUPACAO,
    P.NM_PARTIDO,
    SUM(COALESCE(B.VR_BEM_CANDIDATO, 0)) AS TOTAL_BENS,
    V.QT_VOTOS_NOMINAIS,
    RS.DS_URL AS LINK_REDE_SOCIAL
FROM 
    CANDIDATO C
JOIN 
    OCUPACAO O ON C.CD_OCUPACAO = O.CD_OCUPACAO
JOIN 
    PARTIDO P ON C.NR_PARTIDO = P.NR_PARTIDO
JOIN 
    VOTACAO V ON C.SQ_CANDIDATO = V.SQ_CANDIDATO
JOIN 
    REDE_SOCIAL RS ON C.SQ_CANDIDATO = RS.SQ_CANDIDATO
LEFT JOIN 
    BEM_CANDIDATO B ON C.SQ_CANDIDATO = B.SQ_CANDIDATO
GROUP BY 
    C.NM_CANDIDATO, O.DS_OCUPACAO, P.NM_PARTIDO, V.QT_VOTOS_NOMINAIS, RS.DS_URL
HAVING
    SUM(COALESCE(B.VR_BEM_CANDIDATO, 0)) > 0

SELECT * 
FROM Vw_Candidatos_Informacoes
ORDER BY TRIM(NM_CANDIDATO);
