IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'SiriusTSE')
BEGIN
    CREATE DATABASE SiriusTSE;
END;
GO 

USE SiriusTSE;
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TIPO_BEM')
DROP TABLE dbo.TIPO_BEM;
GO


CREATE TABLE TIPO_BEM (
    CD_TIPO_BEM_CANDIDATO INT PRIMARY KEY, 
    DS_TIPO_BEM_CANDIDATO VARCHAR(255) NOT NULL
);

PRINT 'Criação da tabela TIPO_BEM concluída! ^-^';

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'BEM_CANDIDATO')
DROP TABLE dbo.BEM_CANDIDATO;
GO

CREATE TABLE BEM_CANDIDATO (
    SQ_CANDIDATO BIGINT NOT NULL, 
    NR_ORDEM_BEM_CANDIDATO INT NOT NULL, 
	CD_ELEICAO INT NOT NULL,
	SG_UF CHAR(2),
    SG_UE VARCHAR(10),
	CD_TIPO_BEM_CANDIDATO INT,
    DS_BEM_CANDIDATO VARCHAR(255), 
    VR_BEM_CANDIDATO DECIMAL(20,2) NOT NULL, 
    DT_ULT_ATUAL_BEM_CANDIDATO DATE, 
    HH_ULT_ATUAL_BEM_CANDIDATO TIME,
    PRIMARY KEY (SQ_CANDIDATO, NR_ORDEM_BEM_CANDIDATO),
	FOREIGN KEY (CD_TIPO_BEM_CANDIDATO) REFERENCES TIPO_BEM(CD_TIPO_BEM_CANDIDATO) 
);

PRINT 'Criação da tabela BEM_CANDIDATO concluída! ^-^';





