USE SiriusTSE;
GO

WITH BemMaximo AS (
    SELECT 
        SQ_CANDIDATO,
        MAX(VR_BEM_CANDIDATO) AS MAIOR_BEM
    FROM 
        BEM_CANDIDATO
    GROUP BY 
        SQ_CANDIDATO
)
SELECT 
    C.NM_CANDIDATO,
    C.NM_URNA_CANDIDATO,
    Ca.DS_CARGO,
    BM.MAIOR_BEM,
    B.DS_BEM_CANDIDATO AS NOME_BEM_MAIOR,
    SUM(B.VR_BEM_CANDIDATO) AS PATRIMONIO_TOTAL,
    CASE
        WHEN SUM(B.VR_BEM_CANDIDATO) BETWEEN 0 AND 999999.99 THEN 'Patrimônio Normal'
        WHEN SUM(B.VR_BEM_CANDIDATO) BETWEEN 1000000 AND 999999999.99 THEN 'Patrimônio Milionário'
        WHEN SUM(B.VR_BEM_CANDIDATO) > 1000000000 THEN 'Patrimônio Bilionário'
    END AS CLASSIFICACAO_PATRIMONIAL
FROM 
    CANDIDATO C
JOIN 
    BEM_CANDIDATO B ON C.SQ_CANDIDATO = B.SQ_CANDIDATO
JOIN 
    CARGO Ca ON C.CD_CARGO = Ca.CD_CARGO
JOIN 
    BemMaximo BM ON BM.SQ_CANDIDATO = C.SQ_CANDIDATO AND BM.MAIOR_BEM = B.VR_BEM_CANDIDATO
WHERE 
    C.CD_CARGO IN (SELECT CD_CARGO FROM CARGO WHERE DS_CARGO IN ('VEREADOR', 'PREFEITO', 'VICE-PREFEITO'))
GROUP BY 
    C.SQ_CANDIDATO, C.NM_CANDIDATO, C.NM_URNA_CANDIDATO, Ca.DS_CARGO, B.DS_BEM_CANDIDATO, BM.MAIOR_BEM
ORDER BY 
    PATRIMONIO_TOTAL DESC;