USE SiriusTSE;
GO

SELECT 
    V.NM_MUNICIPIO, 
    C.NM_CANDIDATO,
    V.NR_TURNO,
    ST.DS_SIT_TOT_TURNO,
    SUM(V.QT_VOTOS_NOMINAIS) AS TOTAL_VOTOS
FROM 
    VOTACAO V
JOIN 
    CANDIDATO C ON V.SQ_CANDIDATO = C.SQ_CANDIDATO 
    AND V.NR_TURNO = C.NR_TURNO
JOIN 
    CARGO Ca ON C.CD_CARGO = Ca.CD_CARGO
JOIN 
    SITUACAO_TURNO ST ON V.CD_SIT_TOT_TURNO = ST.CD_SIT_TOT_TURNO
WHERE 
    Ca.DS_CARGO = 'PREFEITO'  
    AND V.SG_UF = 'BA'         
    AND V.NM_MUNICIPIO = 'Candeias' 
GROUP BY 
    V.NM_MUNICIPIO, 
    C.NM_CANDIDATO, 
    V.NR_TURNO, 
    ST.DS_SIT_TOT_TURNO
ORDER BY 
    V.NR_TURNO, 
    TOTAL_VOTOS DESC;