USE SiriusTSE;
GO

SELECT 
    C.NM_CANDIDATO,
    C.NM_URNA_CANDIDATO,
    V.QT_VOTOS_NOMINAIS_VALIDOS AS VOTOS_RECEBIDOS,
    V.NM_MUNICIPIO AS CIDADE,
	St.DS_SIT_TOT_TURNO AS SITUACAO,
    RANK() OVER (ORDER BY V.QT_VOTOS_NOMINAIS_VALIDOS DESC) AS RANKING
FROM 
    CANDIDATO C
JOIN 
    VOTACAO V ON C.SQ_CANDIDATO = V.SQ_CANDIDATO AND C.CD_ELEICAO = V.CD_ELEICAO AND C.NR_TURNO = V.NR_TURNO
JOIN 
    CARGO Ca ON C.CD_CARGO = Ca.CD_CARGO
JOIN 
    SITUACAO_CANDIDATURA Sc ON C.CD_SITUACAO_CANDIDATURA = Sc.CD_SITUACAO_CANDIDATURA
JOIN 
    SITUACAO_TURNO St ON V.CD_SIT_TOT_TURNO = St.CD_SIT_TOT_TURNO
WHERE 
    Ca.DS_CARGO = 'VEREADOR' 
    AND St.DS_SIT_TOT_TURNO IN ('ELEITO', 'ELEITO POR MÉDIA', 'ELEITO POR QP') 
    AND V.NM_MUNICIPIO = 'Candeias' 
	AND V.SG_UF = 'BA'
ORDER BY 
    VOTOS_RECEBIDOS DESC;