USE SiriusTSE;
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SITUACAO_TURNO')
DROP TABLE dbo.SITUACAO_TURNO;
GO

CREATE TABLE SITUACAO_TURNO (
    CD_SIT_TOT_TURNO INT NOT NULL, 
    DS_SIT_TOT_TURNO VARCHAR(100) NOT NULL, 
	PRIMARY KEY (CD_SIT_TOT_TURNO)
);

PRINT 'Criação da tabela SITUACAO_TURNO concluída! ^-^';

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'VOTACAO')
DROP TABLE dbo.VOTACAO;
GO

CREATE TABLE VOTACAO (
	SQ_CANDIDATO BIGINT NOT NULL,
	CD_ELEICAO INT NOT NULL,
	NR_TURNO INT NOT NULL,
    SG_UF CHAR(2) NOT NULL, 
	CD_SIT_TOT_TURNO INT NOT NULL,
    CD_MUNICIPIO INT NOT NULL, 
    NM_MUNICIPIO VARCHAR(100) NOT NULL, 
    NR_ZONA INT NOT NULL, 
	ST_VOTO_EM_TRANSITO CHAR(1) CHECK (ST_VOTO_EM_TRANSITO IN ('S', 'N')), 
    QT_VOTOS_NOMINAIS INT NOT NULL, 
	NM_TIPO_DESTINACAO_VOTOS VARCHAR(50) NOT NULL,
    QT_VOTOS_NOMINAIS_VALIDOS INT NOT NULL, 
	PRIMARY KEY (SQ_CANDIDATO, CD_ELEICAO, NR_TURNO, NR_ZONA),
	FOREIGN KEY (CD_SIT_TOT_TURNO) REFERENCES SITUACAO_TURNO(CD_SIT_TOT_TURNO),
);

PRINT 'Criação da tabela VOTACAO concluída! ^-^';
