USE eleicao; 
GO

CREATE TABLE candidato (
    SQ_CANDIDATO BIGINT,
    NR_CANDIDATO BIGINT,
    NM_CANDIDATO NVARCHAR(255),
    NM_URNA_CANDIDATO NVARCHAR(255),
    NM_SOCIAL_CANDIDATO NVARCHAR(255),
    NR_CPF_CANDIDATO VARCHAR(30),
    NR_TITULO_ELEITORAL_CANDIDATO VARCHAR(30),
    SG_UE BIGINT,
    CD_CARGO INT,
    CD_SITUACAO_CANDIDATURA_CH INT,
    CD_PARTIDO_CH INT,
    CD_GRAU_INSTRUCAO INT,
    CD_OCUPACAO INT,
    CD_ELEICAO BIGINT, 
    CD_TIPO_ELEICAO BIGINT, 
	CD_CANDIDATO_CH INT IDENTITY(1,1) PRIMARY KEY,
    CONSTRAINT FK_uf FOREIGN KEY (SG_UE) REFERENCES uf (SG_UE),
    CONSTRAINT FK_cargo FOREIGN KEY (CD_CARGO) REFERENCES cargo (CD_CARGO),
    CONSTRAINT FK_situacao_candidatura FOREIGN KEY (CD_SITUACAO_CANDIDATURA_CH) REFERENCES situacao_candidatura (CD_SITUACAO_CANDIDATURA_CH),
    CONSTRAINT FK_partido FOREIGN KEY (CD_PARTIDO_CH) REFERENCES partido (CD_PARTIDO_CH),
    CONSTRAINT FK_grau_instrucao FOREIGN KEY (CD_GRAU_INSTRUCAO) REFERENCES grau_instrucao (CD_GRAU_INSTRUCAO),
    CONSTRAINT FK_ocupacao FOREIGN KEY (CD_OCUPACAO) REFERENCES ocupacao (CD_OCUPACAO));

WAITFOR DELAY '00:00:05';
WITH analise_candidato AS (
    SELECT 
        DISTINCT
            SQ_CANDIDATO, 
            NR_CANDIDATO, 
            NM_CANDIDATO, 
            NM_URNA_CANDIDATO, 
            NM_SOCIAL_CANDIDATO, 
            NR_CPF_CANDIDATO, 
            NR_TITULO_ELEITORAL_CANDIDATO, 
            u.SG_UE, 
            CD_CARGO, 
            s.CD_SITUACAO_CANDIDATURA_CH, 
            p.CD_PARTIDO_CH, 
            CD_GRAU_INSTRUCAO, 
            CD_OCUPACAO,
            CD_ELEICAO, 
            CD_TIPO_ELEICAO
    FROM dbo.consulta_cand_2024_BRASIL a
    LEFT JOIN uf u ON a.SG_UE  = u.SG_UE 
    LEFT JOIN situacao_candidatura s 
        ON a.CD_SITUACAO_CANDIDATURA = s.CD_SITUACAO_CANDIDATURA 
        AND a.DS_SITUACAO_CANDIDATURA = s.DS_SITUACAO_CANDIDATURA
    LEFT JOIN partido p 
        ON a.SG_PARTIDO = p.SG_PARTIDO
        AND a.TP_AGREMIACAO = p.TP_AGREMIACAO
        AND a.NR_PARTIDO = p.NR_PARTIDO
        AND a.NR_FEDERACAO = p.NR_FEDERACAO
        AND a.NM_FEDERACAO = p.NM_FEDERACAO
        AND a.SG_FEDERACAO = p.SG_FEDERACAO
        AND a.DS_COMPOSICAO_FEDERACAO = p.DS_COMPOSICAO_FEDERACAO
        AND a.SQ_COLIGACAO = p.SQ_COLIGACAO
        AND a.NM_COLIGACAO = p.NM_COLIGACAO
        AND a.DS_COMPOSICAO_COLIGACAO = p.DS_COMPOSICAO_COLIGACAO

)
INSERT INTO candidato 
    (SQ_CANDIDATO, NR_CANDIDATO, NM_CANDIDATO, NM_URNA_CANDIDATO, NM_SOCIAL_CANDIDATO, NR_CPF_CANDIDATO, 
     NR_TITULO_ELEITORAL_CANDIDATO, SG_UE, CD_CARGO, CD_SITUACAO_CANDIDATURA_CH, CD_PARTIDO_CH, CD_GRAU_INSTRUCAO, 
     CD_OCUPACAO, CD_ELEICAO, CD_TIPO_ELEICAO)
SELECT
	Distinct
    SQ_CANDIDATO, 
    NR_CANDIDATO, 
    NM_CANDIDATO, 
    NM_URNA_CANDIDATO, 
    NM_SOCIAL_CANDIDATO, 
    NR_CPF_CANDIDATO, 
    NR_TITULO_ELEITORAL_CANDIDATO, 
    SG_UE, 
    CD_CARGO, 
    CD_SITUACAO_CANDIDATURA_CH, 
    CD_PARTIDO_CH, 
    CD_GRAU_INSTRUCAO, 
    CD_OCUPACAO, 
    CD_ELEICAO, 
    CD_TIPO_ELEICAO
FROM analise_candidato;

GO
