use eleicao
GO

CREATE TABLE eleicao (
	CD_ELEICAO INT,
	CD_TIPO_ELEICAO INT,
    ANO_ELEICAO INT,
	NR_TURNO INT,
    TP_ABRANGENCIA NVARCHAR(255),
    NM_TIPO_ELEICAO NVARCHAR(255),
    DS_ELEICAO NVARCHAR(255),
    DT_ELEICAO DATE,
    PRIMARY KEY (CD_ELEICAO, CD_TIPO_ELEICAO)  
);

WAITFOR DELAY '00:00:05';

INSERT INTO eleicao (CD_ELEICAO, CD_TIPO_ELEICAO, ANO_ELEICAO, NR_TURNO, TP_ABRANGENCIA, NM_TIPO_ELEICAO, DS_ELEICAO, DT_ELEICAO)
SELECT DISTINCT
 	CD_ELEICAO,
	CD_TIPO_ELEICAO,
    ANO_ELEICAO,
	NR_TURNO,
    TP_ABRANGENCIA,
    NM_TIPO_ELEICAO,
    DS_ELEICAO,
    DT_ELEICAO
	FROM dbo.consulta_cand_2024_BRASIL

GO

select *from dbo.eleicao