use eleicao 

GO

CREATE TABLE grau_instrucao (
    CD_GRAU_INSTRUCAO INT PRIMARY KEY,
    DS_GRAU_INSTRUCAO NVARCHAR(255)
);

WAITFOR DELAY '00:00:05';

INSERT INTO grau_instrucao (CD_GRAU_INSTRUCAO, DS_GRAU_INSTRUCAO)
SELECT
  DISTINCT
    CASE 
        WHEN CD_GRAU_INSTRUCAO IS NULL THEN 9999
        ELSE CD_GRAU_INSTRUCAO 
    END AS CD_GRAU_INSTRUCAO,  
    DS_GRAU_INSTRUCAO
FROM dbo.consulta_cand_2024_Brasil

GO