use eleicao 
GO
CREATE TABLE ocupacao (
    CD_OCUPACAO INT PRIMARY KEY,
    DS_OCUPACAO NVARCHAR(255)
);

WAITFOR DELAY '00:00:05';

INSERT INTO ocupacao (CD_OCUPACAO, DS_OCUPACAO)
SELECT
  DISTINCT
    CASE 
        WHEN CD_OCUPACAO IS NULL THEN 9999
        ELSE CD_OCUPACAO 
    END AS CD_OCUPACAO,  
    DS_OCUPACAO
FROM dbo.consulta_cand_2024_Brasil

GO