use eleicao 

GO

CREATE TABLE situacao_candidatura (
	CD_SITUACAO_CANDIDATURA_CH INT IDENTITY(1,1) PRIMARY KEY,
    CD_SITUACAO_CANDIDATURA INT,
    DS_SITUACAO_CANDIDATURA NVARCHAR(255)
);

WAITFOR DELAY '00:00:05';

INSERT INTO situacao_candidatura (CD_SITUACAO_CANDIDATURA, DS_SITUACAO_CANDIDATURA)
SELECT 
DISTINCT
    CD_SITUACAO_CANDIDATURA,
    DS_SITUACAO_CANDIDATURA
FROM dbo.consulta_cand_2024_BRASIL

GO