USE eleicao;
GO

CREATE TABLE votacao (
    ST_VOTO_EM_TRANSITO VARCHAR(10),
    QT_VOTOS_NOMINAIS BIGINT,
    NM_TIPO_DESTINACAO_VOTOS VARCHAR(100),
    QT_VOTOS_NOMINAIS_VALIDOS BIGINT,
    CD_DETALHE_SITUACAO_CAND BIGINT,
    CD_SIT_TOT_TURNO INT,
    SQ_CANDIDATO BIGINT,
	CD_MUNICIPIO BIGINT,
	NR_ZONA BIGINT,
	CD_CARGO BIGINT,
    PRIMARY KEY (QT_VOTOS_NOMINAIS,SQ_CANDIDATO, CD_MUNICIPIO, NR_ZONA,CD_CARGO),
    FOREIGN KEY (CD_SIT_TOT_TURNO) REFERENCES situacao_turno(CD_SIT_TOT_TURNO)

);

WAITFOR DELAY '00:00:05';

INSERT INTO votacao ( 
	ST_VOTO_EM_TRANSITO,
    QT_VOTOS_NOMINAIS,
    NM_TIPO_DESTINACAO_VOTOS ,
    QT_VOTOS_NOMINAIS_VALIDOS ,
    CD_DETALHE_SITUACAO_CAND ,
    CD_SIT_TOT_TURNO,
    SQ_CANDIDATO ,
	CD_MUNICIPIO ,
	NR_ZONA ,
	CD_CARGO)
select 
	Distinct
    ST_VOTO_EM_TRANSITO,
    QT_VOTOS_NOMINAIS,
    NM_TIPO_DESTINACAO_VOTOS ,
    QT_VOTOS_NOMINAIS_VALIDOS ,
    CD_DETALHE_SITUACAO_CAND ,
    CD_SIT_TOT_TURNO,
    SQ_CANDIDATO ,
	CD_MUNICIPIO ,
	NR_ZONA ,
	CD_CARGO
from votacao_candidato_munzona_2024_BRASIL