-- 2 - UF (Aproveitar a mesma tabela criada na Atividade 01)
-- Já carregada em Script - Atividade 1 Script 2.sql

-- 3 - Tipo de Bem
INSERT INTO Tipo_Bem (CD_TIPO_BEM_CANDIDATO, DS_TIPO_BEM_CANDIDATO)
SELECT DISTINCT CD_TIPO_BEM_CANDIDATO, DS_TIPO_BEM_CANDIDATO
FROM carga_bem_candidato

-- 1 - Bens de Candidato;
INSERT INTO Bem_Candidato (SQ_CANDIDATO, CD_ELEICAO, NR_ORDEM_BEM_CANDIDATO, CD_TIPO_BEM_CANDIDATO, DS_BEM_CANDIDATO, VR_BEM_CANDIDATO, DT_ULT_ATUAL_BEM_CANDIDATO, HH_ULT_ATUAL_BEM_CANDIDATO)
SELECT TRIM(SQ_CANDIDATO), CD_ELEICAO, NR_ORDEM_BEM_CANDIDATO, CD_TIPO_BEM_CANDIDATO, DS_BEM_CANDIDATO, CAST(REPLACE(VR_BEM_CANDIDATO, ',', '.') AS DECIMAL(18, 2)), CONVERT(DATE, DT_ULT_ATUAL_BEM_CANDIDATO, 103), HH_ULT_ATUAL_BEM_CANDIDATO
FROM carga_bem_candidato