-- 2 - UF
-- Já criada em Script - Atividade 1 Script 1.sql

-- 4 - Eleição
-- Já criada em Script - Atividade 1 Script 1.sql

-- 5 - Candidato
-- Já criada em Script - Atividade 1 Script 1.sql

-- 3 - Tipo de Rede Social
CREATE TABLE [Tipo_Rede_Social] (
  [CD_TIPO_REDE_SOCIAL] tinyint NOT NULL,
  [DS_TIPO_REDE_SOCIAL] varchar(100) NULL,
  PRIMARY KEY CLUSTERED ([CD_TIPO_REDE_SOCIAL])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 1 - Rede Social
CREATE TABLE [Rede_Social] (
  [SQ_CANDIDATO] char(12) NOT NULL,
  [CD_ELEICAO] smallint NOT NULL,
  [NR_ORDEM_REDE_SOCIAL] tinyint NOT NULL,
  [CD_TIPO_REDE_SOCIAL] tinyint NULL,
  [DS_URL] varchar(255			) NULL,
  PRIMARY KEY CLUSTERED ([SQ_CANDIDATO], [CD_ELEICAO], [NR_ORDEM_REDE_SOCIAL])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

ALTER TABLE [dbo].[Rede_Social] ADD CONSTRAINT [FK_REDE_SOCIAL_TIPO_REDE_SOCIAL] FOREIGN KEY ([CD_TIPO_REDE_SOCIAL]) REFERENCES [dbo].[Tipo_Rede_Social] ([CD_TIPO_REDE_SOCIAL])
GO
ALTER TABLE [dbo].[Rede_Social] ADD CONSTRAINT [FK_REDE_SOCIAL_CANDIDATO] FOREIGN KEY ([SQ_CANDIDATO], [CD_ELEICAO]) REFERENCES [dbo].[Candidato] ([SQ_CANDIDATO], [CD_ELEICAO])
GO