-- 2 - UF (Aproveitar a mesma tabela criada na Atividade 01);
-- Já criada
CREATE TABLE [Unidade_Federacao] (
  [SG_UF] char(2) NOT NULL,
  [DS_UF] varchar(100) NULL,
  PRIMARY KEY CLUSTERED ([SG_UF])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 3 - Tipo de Bem;
CREATE TABLE [Tipo_Bem] (
  [CD_TIPO_BEM_CANDIDATO] tinyint NOT NULL,
  [DS_TIPO_BEM_CANDIDATO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_TIPO_BEM_CANDIDATO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 1 - Bens de Candidato;
CREATE TABLE [Bem_Candidato] (
  [SQ_CANDIDATO] char(12) NOT NULL,
  [CD_ELEICAO] smallint NOT NULL,
  [NR_ORDEM_BEM_CANDIDATO] smallint NOT NULL,
  [CD_TIPO_BEM_CANDIDATO] tinyint NULL,
  [DS_BEM_CANDIDATO] varchar(255) NULL,
  [VR_BEM_CANDIDATO] decimal(18,2) NULL,
  [DT_ULT_ATUAL_BEM_CANDIDATO] date NULL,
  [HH_ULT_ATUAL_BEM_CANDIDATO] time NULL,
  PRIMARY KEY CLUSTERED ([SQ_CANDIDATO], [NR_ORDEM_BEM_CANDIDATO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

ALTER TABLE [Bem_Candidato] ADD CONSTRAINT [FK_BEM_TIPO_BEM] FOREIGN KEY ([CD_TIPO_BEM_CANDIDATO]) REFERENCES [Tipo_Bem] ([CD_TIPO_BEM_CANDIDATO])
GO
ALTER TABLE [Bem_Candidato] ADD CONSTRAINT [FK_BEM_CANDIDATO] FOREIGN KEY ([SQ_CANDIDATO], [CD_ELEICAO]) REFERENCES [Candidato] ([SQ_CANDIDATO], [CD_ELEICAO])
GO
