-- 2 – UF;
CREATE TABLE [Unidade_Federacao] (
  [SG_UF] char(2) NOT NULL,
  [DS_UF] varchar(100) NULL,
  PRIMARY KEY CLUSTERED ([SG_UF])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 3 – Cargo;
CREATE TABLE [Cargo] (
  [CD_CARGO] tinyint NOT NULL,
  [DS_CARGO] varchar(30) NULL,
  PRIMARY KEY CLUSTERED ([CD_CARGO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 4 – Situação Candidatura;
CREATE TABLE [Situacao_Candidatura] (
  [CD_SITUACAO_CANDIDATURA] tinyint NOT NULL,
  [DS_SITUACAO_CANDIDATURA] varchar(100) NULL,
  PRIMARY KEY CLUSTERED ([CD_SITUACAO_CANDIDATURA])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 5 – Partido;
CREATE TABLE [Partido] (
  [NR_PARTIDO] tinyint NOT NULL,
  [SG_PARTIDO] varchar(20) NULL,
  [NM_PARTIDO] varchar(50) NULL,
  PRIMARY KEY CLUSTERED ([NR_PARTIDO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 6 – Grau de Instrução;
CREATE TABLE [Grau_Instrucao] (
  [CD_GRAU_INSTRUCAO] tinyint NOT NULL,
  [DS_GRAU_INSTRUCAO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_GRAU_INSTRUCAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 7 – Ocupação;
CREATE TABLE [Ocupacao] (
  [CD_OCUPACAO] smallint NOT NULL,
  [DS_OCUPACAO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_OCUPACAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 8 – Eleição.
CREATE TABLE [Eleicao] (
  [CD_ELEICAO] smallint NOT NULL,
  [CD_TIPO_ELEICAO] tinyint NULL,
  [TP_ABRANGENCIA] varchar(30) NULL,
  [ANO_ELEICAO] smallint NULL,
  [DS_ELEICAO] varchar(100) NULL,
  [DT_ELEICAO] date NULL,
  PRIMARY KEY CLUSTERED ([CD_ELEICAO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- Extras
CREATE TABLE [Unidade_Eleitoral] (
  [SG_UE] int NOT NULL,
  [NM_UE] varchar(255) NULL,
  [SG_UF] char(2) NULL,
  PRIMARY KEY CLUSTERED ([SG_UE])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

ALTER TABLE [Unidade_Eleitoral] ADD CONSTRAINT [FK_UE_UF] FOREIGN KEY ([SG_UF]) REFERENCES [Unidade_Federacao] ([SG_UF])
GO

CREATE TABLE [Situacao_Julgamento] (
  [CD_SITUACAO_JULGAMENTO] tinyint NOT NULL,
  [DS_SITUACAO_JULGAMENTO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_SITUACAO_JULGAMENTO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

CREATE TABLE [Situacao_Totalizacao_Turno] (
  [CD_SIT_TOT_TURNO] tinyint NOT NULL,
  [DS_SIT_TOT_TURNO] varchar(255) NULL,
  PRIMARY KEY CLUSTERED ([CD_SIT_TOT_TURNO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

-- 1 – Candidato;
CREATE TABLE [Candidato] (
  [SQ_CANDIDATO] char(12) NOT NULL,  
  [CD_ELEICAO] smallint NOT NULL,
  [NR_CPF_CANDIDATO] char(11) NULL,
  [DS_EMAIL] varchar(255) NULL,
  [NM_CANDIDATO] varchar(255) NULL,
  [NM_SOCIAL_CANDIDATO] varchar(255) NULL,
  [SG_UF_NASCIMENTO] char(2) NULL,
  [DT_NASCIMENTO] date NULL,
  [NR_TITULO_ELEITORAL_CANDIDATO] varchar(15) NULL,
  [CD_GENERO] tinyint NULL,
  [CD_GRAU_INSTRUCAO] tinyint NULL,
  [CD_ESTADO_CIVIL] tinyint NULL,
  [CD_COR_RACA] char(2) NULL,
  [CD_OCUPACAO] smallint NULL,
  [SG_UE] int NULL,
  [CD_CARGO] tinyint NULL,
  [NR_CANDIDATO] int NULL,
  [NM_URNA_CANDIDATO] varchar(100) NULL,
  [CD_SITUACAO_CANDIDATURA] tinyint NULL,
  [NR_PARTIDO] tinyint NULL,
  [CD_SIT_TOT_TURNO] tinyint NULL,
  [CD_SITUACAO_JULGAMENTO] tinyint NULL,
  --[CD_SITUACAO_DIPLOMA] smallint NULL,
  --[CD_SITUACAO_CASSACAO] smallint NULL,
  --[CD_DETALHE_SITUACAO_CAND] smallint NULL,
  PRIMARY KEY CLUSTERED ([CD_ELEICAO], [SQ_CANDIDATO])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_OCUPACAO] FOREIGN KEY ([CD_OCUPACAO]) REFERENCES [Ocupacao] ([CD_OCUPACAO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_GRAU_INSTRUCAO] FOREIGN KEY ([CD_GRAU_INSTRUCAO]) REFERENCES [Grau_Instrucao] ([CD_GRAU_INSTRUCAO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_ELEICAO] FOREIGN KEY ([CD_ELEICAO]) REFERENCES [Eleicao] ([CD_ELEICAO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_PARTIDO] FOREIGN KEY ([NR_PARTIDO]) REFERENCES [Partido] ([NR_PARTIDO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_SITUACAO_CANDIDATURA] FOREIGN KEY ([CD_SITUACAO_CANDIDATURA]) REFERENCES [Situacao_Candidatura] ([CD_SITUACAO_CANDIDATURA])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_CARGO] FOREIGN KEY ([CD_CARGO]) REFERENCES [Cargo] ([CD_CARGO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_UNIDADE_ELEITORAL] FOREIGN KEY ([SG_UE]) REFERENCES [Unidade_Eleitoral] ([SG_UE])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_SITUACAO_JULGAMENTO] FOREIGN KEY ([CD_SIT_TOT_TURNO]) REFERENCES [Situacao_Julgamento] ([CD_SIT_TOT_TURNO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_SITUACAO_TOTALIZACAO_TURNO] FOREIGN KEY ([CD_SIT_TOT_TURNO]) REFERENCES [Situacao_Totalizacao_Turno] ([CD_SIT_TOT_TURNO])
GO
ALTER TABLE [Candidato] ADD CONSTRAINT [FK_CANDIDATO_UF_NASCIMENTO] FOREIGN KEY ([SG_UF_NASCIMENTO]) REFERENCES [dbo].[Unidade_Federacao] ([SG_UF])
GO